server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/b2b_inventory
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_null
